pipeline {
    agent any 
    environment {
    DOCKERHUB_CREDENTIALS = credentials('lankateju-docker')
    }
    stages { 
        stage('SCM Checkout') {
            steps{
            git ' https://github.com/heroku/node-js-getting-started.git'
            }
        }

        stage('Build docker image') {
            steps {  
                sh 'docker build -t lankateju/nodeapp:$BUILD_NUMBER .'
            }
        }
        stage('login to dockerhub') {
            steps{
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('push image') {
            steps{
                sh 'docker push lankateju/nodeapp:$BUILD_NUMBER'
            }
        }
}
post {
        always {
            sh 'docker logout'
        }
    }
}
#https://github.com/heroku/node-js-getting-started.git is is a Git repository for a Node.js application, not a Docker image
#So to create a Docker image for a Node.js application, we sould typically write a Dockerfile and then build the image using the docker build command.
#installed jenkins and docker on the same server
#Grant jenkins user and ubuntu user permisson to docker deamon
#Installed required plugins in jenkins
#After that used above a Jenkins pipeline script to automate the process of building and pushing the Docker image
