pipeline {
    agent any 
    environment {
    DOCKERHUB_CREDENTIALS = credentials('lankateju-docker')
    }
    stages { 
        stage('SCM Checkout') {
            steps{
            git ' https://github.com/heroku/node-js-getting-started.git'
            }
        }

        stage('Build docker image') {
            steps {  
                sh 'docker build -t lankateju/nodeapp:$BUILD_NUMBER .'
            }
        }
        stage('login to dockerhub') {
            steps{
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('push image') {
            steps{
                sh 'docker push lankateju/nodeapp:$BUILD_NUMBER'
            }
        }
}
post {
        always {
            sh 'docker logout'
        }
    }
}
